"""Builds and stores the /map page's pre-computed catchment overview
FeatureCollection (see MapCatchmentsCache in packages/database/prisma/
schema.prisma). Regenerated by the refresh-catchment-overview-cache CLI
command; must be re-run after any catchment import or refresh-catchment-
scores, same as that command's own "re-run after either changes" rule.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from catchment_zone_ingestor import db

#: Matches the precision the API route previously applied per-request
#: (roundCoordinates in apps/web/app/api/map/catchments/route.ts) - kept in
#: sync deliberately, not derived from a shared constant, since the two
#: live in different languages/packages.
COORDINATE_DECIMAL_PLACES = 5


@dataclass
class CatchmentAreaCacheRow:
    id: str
    area_name: str
    area_type: str
    academic_year: str
    overview_geometry_geojson: str
    performance_percentile: float | None
    performance_metric_code: str | None


def load_rows(conn: db.ConnectionLike) -> list[CatchmentAreaCacheRow]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT id, area_name, area_type, academic_year, overview_geometry_geojson,
                   performance_percentile, performance_metric_code
            FROM catchment_areas
            """
        )
        return [
            CatchmentAreaCacheRow(
                id=row["id"],
                area_name=row["area_name"],
                area_type=row["area_type"],
                academic_year=row["academic_year"],
                overview_geometry_geojson=row["overview_geometry_geojson"],
                performance_percentile=row["performance_percentile"],
                performance_metric_code=row["performance_metric_code"],
            )
            for row in cur.fetchall()
        ]


def _round_coordinates(node: Any) -> Any:
    if isinstance(node, list):
        if len(node) >= 2 and isinstance(node[0], int | float) and isinstance(node[1], int | float):
            return [
                round(value, COORDINATE_DECIMAL_PLACES) if isinstance(value, int | float) else value
                for value in node
            ]
        return [_round_coordinates(item) for item in node]
    return node


def build_feature_collection_json(conn: db.ConnectionLike) -> tuple[str, int]:
    rows = load_rows(conn)
    features = []
    for row in rows:
        try:
            geometry = json.loads(row.overview_geometry_geojson)
        except json.JSONDecodeError:
            # Same policy as the API route: skip one malformed stored
            # geometry rather than fail the whole cache build.
            continue
        features.append(
            {
                "type": "Feature",
                "geometry": {
                    "type": geometry["type"],
                    "coordinates": _round_coordinates(geometry["coordinates"]),
                },
                "properties": {
                    "id": row.id,
                    "areaName": row.area_name,
                    "areaType": row.area_type,
                    "academicYear": row.academic_year,
                    "performancePercentile": row.performance_percentile,
                    "performanceMetricCode": row.performance_metric_code,
                },
            }
        )
    feature_collection = {"type": "FeatureCollection", "features": features}
    return json.dumps(feature_collection, separators=(",", ":")), len(features)


def write_cache(conn: db.ConnectionLike, feature_collection_json: str, feature_count: int) -> None:
    with db.transaction(conn), conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO map_catchments_cache (id, feature_collection_json, feature_count, generated_at)
            VALUES ('current', %(feature_collection_json)s, %(feature_count)s, now())
            ON CONFLICT (id) DO UPDATE SET
                feature_collection_json = EXCLUDED.feature_collection_json,
                feature_count = EXCLUDED.feature_count,
                generated_at = EXCLUDED.generated_at
            """,
            {
                "feature_collection_json": feature_collection_json,
                "feature_count": feature_count,
            },
        )


def refresh_catchment_overview_cache(conn: db.ConnectionLike) -> int:
    feature_collection_json, feature_count = build_feature_collection_json(conn)
    write_cache(conn, feature_collection_json, feature_count)
    return feature_count
