"""Tests for the Scotland school performance adapter (statistics.gov.scot's
"Schools - Attainment for All" and "Schools - Attainment by Deprivation"
datasets).

The CSVs below are shaped exactly like each real dataset's response
(header rows, aggregate group rows, "#" suppression marker), verified
live against statistics.gov.scot on 2026-08-03, but with invented school
names/ids and values.
"""

from __future__ import annotations

import httpx
import pytest

from catchment_zone_ingestor.adapters import scotland_performance
from catchment_zone_ingestor.adapters.scotland_performance import (
    METRIC_CODE_HIGHEST_20,
    METRIC_CODE_LOWEST_20,
    METRIC_CODE_MIDDLE_60,
    METRIC_CODE_SIMD_Q1_MOST_DEPRIVED,
    METRIC_CODE_SIMD_Q3,
    METRIC_CODE_SIMD_Q5_LEAST_DEPRIVED,
    academic_year_label,
    fetch_all_years_performance,
    parse_attainment_csv,
)

_SAMPLE_CSV = """Generated by http://statistics.gov.scot,2026-08-03T14:33:28+00:00
http://statistics.gov.scot/data/attainment-for-all,Schools - Attainment for All
measure type,Average Total Tariff Score
Reference Period,Academic year 2024-25
School Comparator,Real Establishment
Measure (cell values): ,Average Total Tariff Score(Tariff Points)

,,http://statistics.gov.scot/def/concept/attainment-distribution/lowest-20,http://statistics.gov.scot/def/concept/attainment-distribution/middle-60,http://statistics.gov.scot/def/concept/attainment-distribution/highest-20
http://statistics.gov.scot/def/education/refEstablishment,Reference Establishment,Lowest 20%,Middle 60%,Highest 20%
http://statistics.gov.scot/id/education/establishment-group/900,Grant Aided,983,1867,2374
http://statistics.gov.scot/id/education/establishment-group/1,National,132,874,1965
http://statistics.gov.scot/id/education/establishment/9999001,Test Academy,508,1608,2452
http://statistics.gov.scot/id/education/establishment/9999002,Test Junior High School,#,#,#
http://statistics.gov.scot/id/education/establishment/9999999,Unregistered Academy,100,200,300
http://statistics.gov.scot/id/education/establishment/9999003,Test Rural School,*,712,*
"""

_DEPRIVATION_SAMPLE_CSV = """Generated by http://statistics.gov.scot,2026-08-03T15:02:11+00:00
http://statistics.gov.scot/data/attainment-by-deprivation-quintile,Schools - Attainment by Deprivation
measure type,Average Total Tariff Score
Reference Period,Academic year 2024-25
School Comparator,Real Establishment
Measure (cell values): ,Average Total Tariff Score(Tariff Points)

,,http://statistics.gov.scot/def/concept/simd-quintiles/1-most-deprived,http://statistics.gov.scot/def/concept/simd-quintiles/2,http://statistics.gov.scot/def/concept/simd-quintiles/3,http://statistics.gov.scot/def/concept/simd-quintiles/4,http://statistics.gov.scot/def/concept/simd-quintiles/5-least-deprived
http://statistics.gov.scot/def/education/refEstablishment,Reference Establishment,1 - most deprived,2,3,4,5 - least deprived
http://statistics.gov.scot/id/education/establishment-group/900,Grant Aided,983,1867,2374,1200,1500
http://statistics.gov.scot/id/education/establishment-group/1,National,676,786,907,1072,1311
http://statistics.gov.scot/id/education/establishment/9999001,Test Academy,1049,1384,1343,1706,1682
"""


def test_academic_year_label() -> None:
    assert academic_year_label(2024) == "2024-2025"


def test_parses_real_schools_only_skips_aggregate_groups() -> None:
    metrics, _skipped = parse_attainment_csv(_SAMPLE_CSV, 2024, known_urns={"9999001S", "9999002S"})
    urns = {m.school_urn for m in metrics}
    assert urns == {"9999001S", "9999002S"}


def test_skips_schools_not_in_known_urns() -> None:
    metrics, skipped = parse_attainment_csv(_SAMPLE_CSV, 2024, known_urns={"9999001S"})
    assert all(m.school_urn != "9999999S" for m in metrics)
    assert "9999999S" in skipped


def test_appends_s_suffix_to_seed_code() -> None:
    metrics, _skipped = parse_attainment_csv(_SAMPLE_CSV, 2024, known_urns={"9999001S"})
    assert all(m.school_urn == "9999001S" for m in metrics)


def test_three_metrics_per_school() -> None:
    metrics, _skipped = parse_attainment_csv(_SAMPLE_CSV, 2024, known_urns={"9999001S"})
    codes = {m.metric_code for m in metrics}
    assert codes == {METRIC_CODE_LOWEST_20, METRIC_CODE_MIDDLE_60, METRIC_CODE_HIGHEST_20}


def test_parses_real_values_correctly() -> None:
    metrics, _skipped = parse_attainment_csv(_SAMPLE_CSV, 2024, known_urns={"9999001S"})
    middle60 = next(m for m in metrics if m.metric_code == METRIC_CODE_MIDDLE_60)
    assert middle60.value_numeric == pytest.approx(1608)
    assert middle60.suppressed is False


def test_suppressed_marker_stored_not_dropped() -> None:
    metrics, _skipped = parse_attainment_csv(_SAMPLE_CSV, 2024, known_urns={"9999002S"})
    assert len(metrics) == 3
    assert all(m.suppressed is True for m in metrics)
    assert all(m.value_numeric is None for m in metrics)


def test_asterisk_marker_also_treated_as_suppressed() -> None:
    """Verified live: some rural schools suppress only one or two bands
    with "*" (too few leavers to safely split that specific quintile)
    while another band on the same row has a real value - a different
    marker to "#" but the same real-suppression meaning."""
    metrics, _skipped = parse_attainment_csv(_SAMPLE_CSV, 2024, known_urns={"9999003S"})
    lowest = next(m for m in metrics if m.metric_code == METRIC_CODE_LOWEST_20)
    middle = next(m for m in metrics if m.metric_code == METRIC_CODE_MIDDLE_60)
    highest = next(m for m in metrics if m.metric_code == METRIC_CODE_HIGHEST_20)
    assert lowest.suppressed is True
    assert highest.suppressed is True
    assert middle.suppressed is False
    assert middle.value_numeric == pytest.approx(712)


def test_academic_year_set_correctly() -> None:
    metrics, _skipped = parse_attainment_csv(_SAMPLE_CSV, 2024, known_urns={"9999001S"})
    assert all(m.academic_year == "2024-2025" for m in metrics)


def test_parses_deprivation_quintile_dataset_with_its_own_spec() -> None:
    """The second dataset (Attainment by Deprivation) is structurally the
    same shape as Attainment for All but with 5 SIMD quintile bands
    instead of 3 attainment bands - parse_attainment_csv must use the
    right spec's band_metric_codes, not the default 3-band one."""
    metrics, _skipped = parse_attainment_csv(
        _DEPRIVATION_SAMPLE_CSV, 2024, known_urns={"9999001S"}, spec=scotland_performance._ATTAINMENT_BY_DEPRIVATION
    )
    codes = {m.metric_code for m in metrics}
    assert codes == {
        METRIC_CODE_SIMD_Q1_MOST_DEPRIVED,
        "scotland_leaver_tariff_simd_q2",
        METRIC_CODE_SIMD_Q3,
        "scotland_leaver_tariff_simd_q4",
        METRIC_CODE_SIMD_Q5_LEAST_DEPRIVED,
    }
    q1 = next(m for m in metrics if m.metric_code == METRIC_CODE_SIMD_Q1_MOST_DEPRIVED)
    assert q1.value_numeric == pytest.approx(1049)
    assert q1.source_release == "statistics.gov.scot/data/attainment-by-deprivation-quintile"


def test_fetch_all_years_tolerates_one_year_failing() -> None:
    """fetch_all_years_performance fetches both datasets (Attainment for
    All, Attainment by Deprivation) for every year - a failure on one
    (dataset, year) pair must not lose any other pair."""

    def handler(request: httpx.Request) -> httpx.Response:
        if "2020-08-01" in request.url.params.get("http://purl.org/linked-data/sdmx/2009/dimension#refPeriod", ""):
            return httpx.Response(500, text="server error")
        return httpx.Response(200, text=_SAMPLE_CSV)

    with httpx.Client(transport=httpx.MockTransport(handler)) as client:
        result = fetch_all_years_performance(client, known_urns={"9999001S", "9999002S"}, year_starts=[2019, 2020, 2021])

    # 2 datasets x 3 years, 1 year fails for both datasets -> 4 succeed.
    assert result.years_fetched == 4
