-- A single-row cache of the /map page's whole-of-Great-Britain catchment
-- overview layer (the complete, pre-serialised FeatureCollection). Fetching
-- and transforming all ~9,000+ catchment_areas rows on every request was
-- the dominant cost in that endpoint - one query for one pre-built row is
-- close to instant by comparison. Regenerated by the ingestor's
-- refresh-catchment-overview-cache command; not a source of truth, always
-- rebuildable from catchment_areas.
CREATE TABLE "map_catchments_cache" (
    "id" STRING NOT NULL DEFAULT 'current',
    "feature_collection_json" STRING NOT NULL,
    "feature_count" INT4 NOT NULL,
    "generated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "map_catchments_cache_pkey" PRIMARY KEY ("id")
) WITH (schema_locked = false);
